config/routes.rb
Rails.application.routes.draw do
  root 'reserve#time_select'
  
  get 'reserve/time_select', to: 'reserve#time_select', as: 'time_select'
  get 'reserve/seat_select/:id', to: 'reserve#seat_select', as: 'seat_select'
  get 'reserve/form/:id', to: 'reserve#form', as: 'reserve_form'
  post 'reserve/register/:id', to: 'reserve#register', as: 'reserve_register'
  get 'reserve/auth/:id', to: 'reserve#auth', as: 'reserve_auth'
  get 'reserve/resend'
  post 'reserve/resend', to: 'reserve#resend_mail', as: 'reserve_resend_mail'
  get 'reserve/cancel_form/:id', to: 'reserve#cancel_form', as: 'reserve_cancel_form'
  post 'reserve/cancel/:id', to: 'reserve#cancel', as: 'reserve_cancel'
  get 'help', to: 'reserve#help'
  get 'reserve/message', to: 'reserve#message', as: 'message'

  get 'admin', to: 'admin#index'
  get 'admin/info', to: 'admin#info'
  get 'admin/login'
  post 'admin/login', to: 'admin#authenticate', as: 'admin_auth'
  delete 'admin/logout', to: 'admin#logout', as: 'admin_logout'
  post 'admin/attend'
  post 'admin/call', to: 'admin#call_mail_send'
  post 'admin/apollo', to: 'admin#apollo_mail_send'
  post 'admin/cancel'

  # if Rails.env.development?
    # mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end

  match '*path' => 'application#rescue404', via: :all
end

app/views/admin/attend.js.erb
if (<%= @attr.attended %>){
  $('#button-<%= @attr.id %>').html('○');
  $('#button-<%= @attr.id %>').css('background-color', '#90EE90');
} else {
  $('#button-<%= @attr.id %>').html('×');
  $('#button-<%= @attr.id %>').css('background-color', 'white');
}

app/views/admin/index.html.erb
<div id="admin-console">
  <h1>管理画面</h1>
  <%= link_to 'ログアウト', admin_logout_path, method: :delete, id: 'logout-button' %>
  <div class="description">
    ---お知らせ---
    <ul>
      <li>公演開始30分前に送るメールの送信は自動化されました。</li>
      <li>公演開始30分前を過ぎて予約した方には30分前メールは送信されません。</li>
      <li>アポロのメールは、予約をして出席した方だけに送信されます。</li>
      <li>そのため、必ず出席した方の出席ボタンを○に変えてから、メールを送信してください。</li>
    </ul>
  </div>
  <table>
    <thead>
    <tr>
      <th>公演時間</th>
      <th>部屋</th>
      <th>座席</th>
      <th>メールアドレス</th>
      <th>認証コード</th>
      <th>予約日時</th>
      <th>値段</th>
      <th>出席</th>
      <th>30分前メール</th>
      <th>アポロメール</th>
      <th>アポロのメール</th>
      <th>削除</th>
    </tr>
    </thead>
    <tbody>
    <% @attrs.each_with_index do |attr, i| %>
      <% if i.between?(90, 99) || i.between?(190, 199) || i.between?(340, 349) || i.between?(440, 449) %>
        <tr>
          <td colspan="11">休憩時間</td>
        </tr>
      <% else %>
        <tr class="<%= 'stripe' if i.to_s[-2].nil? || i.to_s[-2].to_i.even? %>">
          <% if i % 10 == 0 %>
            <td rowspan="10">
              <%= attr.time.strftime("%m/%d %H:%M") %>
            </td>
          <% end %>
          <td>
            <%= seat_is(attr.seat)[0][5] %>
          </td>
          <td>
            <%= seat_is(attr.seat)[1][5..6] %>
          </td>
          <td class="email">
            <%= attr.authenticated_addr %>
          </td>
          <td class="code">
            <% unless attr.user.where(status: 1).empty? %>
              <%= attr.user.where(status: 1).last.url[0..5] %>
            <% end %>
          </td>
          <td>
            <% unless attr.authenticated_at.nil? %>
              <%= time_is(attr.authenticated_at, attr.time) ? '当日' : '前売り' %>
            <% end %>
          </td>
          <td>
            <% unless attr.authenticated_at.nil? %>
              <%= how_much(attr.seat, attr.authenticated_at, attr.time) %>円
            <% end %>
          </td>
          <td>
            <%= form_tag(admin_attend_path, remote: true) do %>
              <%= hidden_field_tag :attr_id, attr.id %>
                <% if attr.attended %>
                  <%= button_tag(id: "button-#{i+1}", class: 'attended') do %>
                    ○
                  <% end %>
                <% else %>
                  <%= button_tag(id: "button-#{i+1}") do %>
                    ×
                  <% end %>
               <% end %>
            <% end %>
          </td>
          <td>
            <%= '済' if attr.mail1 %>
          </td>
          <td>
            <%= '済' if attr.mail2 %>
          </td>
          <% if i%10 == 0 %>
            <td class="mail-button">
              <%= form_tag admin_apollo_path do %>
                <%= hidden_field_tag :attr_time, attr.time %>
                <%= submit_tag 'アポロからのメールを送信',
                               data: { confirm: "アポロのメールを送信します。よろしいですか？"} %>
              <% end %>
            </td>
          <% end %>
          <% if i%10 == 1 %>
            <td>
              <%= '送信済みです' if attr.status == 3 %>
            </td>
          <% end %>
          <td>
            <% if attr.authenticated_addr.present? %>
              <%= form_tag admin_cancel_path do %>
                <%= hidden_field_tag :attr_id, attr.id %>
                <%= submit_tag '削除', data: { confirm: "予約を削除します。よろしいですか？" } %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/info.html.erb
<div id="admin-console">
  <h1>一覧画面</h1>
  <br>
  <table>
    <thead>
    <tr>
      <th>公演時間</th>
      <th>部屋</th>
      <th>座席</th>
      <th>認証コード</th>
      <th>予約日時</th>
      <th>値段</th>
      <th>出席</th>
    </tr>
    </thead>
    <tbody>
      <% @attrs.each_with_index do |attr, i| %>
        <% if i.between?(90, 99) || i.between?(190, 199) || i.between?(340, 349) || i.between?(440, 449) %>
          <tr>
            <td colspan="11">休憩時間</td>
          </tr>
        <% else %>
          <tr class="<%= 'stripe' if i.to_s[-2].nil? || i.to_s[-2].to_i.even? %>">
            <% if i % 10 == 0 %>
                <td rowspan="10">
                  <%= attr.time.strftime("%m/%d %H:%M") %>
                </td>
            <% end %>
            <td>
              <%= seat_is(attr.seat)[0][5] %>
            </td>
            <td>
              <%= seat_is(attr.seat)[1][5..6] %>
            </td>
            <td class="code">
              <% unless attr.user.where(status: 1).empty? %>
                  <%= attr.user.where(status: 1).last.url[0..5] %>
              <% end %>
            </td>
            <td>
              <% unless attr.authenticated_at.nil? %>
                  <%= time_is(attr.authenticated_at, attr.time) ? '当日' : '前売り' %>
              <% end %>
            </td>
            <td>
              <% unless attr.authenticated_at.nil? %>
                  <%= how_much(attr.seat, attr.authenticated_at, attr.time) %>円
              <% end %>
            </td>
            <td>
              <%= form_tag(admin_attend_path, remote: true) do %>
                  <%= hidden_field_tag :attr_id, attr.id %>
                  <% if attr.attended %>
                    <%= button_tag(id: "button-#{i+1}", class: 'attended') do %>
                      ○
                    <% end %>
                  <% else %>
                    <%= button_tag(id: "button-#{i+1}") do %>
                      ×
                    <% end %>
                 <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/login.html.erb
<div id="login">
  <%= form_tag(admin_auth_path) do %>
    <div class="login-form">
      <%= label_tag :username %>
      <%= text_field_tag :username %>
    </div>
    <div class="login-form">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="login-button">
      <%= submit_tag('送信') %>
    </div>
  <% end %>
</div>