config/routes.rb
Rails.application.routes.draw do
  root 'reserve#time_select'
  
  get 'reserve/time_select', to: 'reserve#time_select', as: 'time_select'
  get 'reserve/seat_select/:id', to: 'reserve#seat_select', as: 'seat_select'
  get 'reserve/form/:id', to: 'reserve#form', as: 'reserve_form'
  post 'reserve/register/:id', to: 'reserve#register', as: 'reserve_register'
  get 'reserve/auth/:id', to: 'reserve#auth', as: 'reserve_auth'
  get 'reserve/resend'
  post 'reserve/resend', to: 'reserve#resend_mail', as: 'reserve_resend_mail'
  get 'reserve/cancel_form/:id', to: 'reserve#cancel_form', as: 'reserve_cancel_form'
  post 'reserve/cancel/:id', to: 'reserve#cancel', as: 'reserve_cancel'
  get 'help', to: 'reserve#help'
  get 'reserve/message', to: 'reserve#message', as: 'message'

  get 'admin', to: 'admin#index'
  get 'admin/info', to: 'admin#info'
  get 'admin/login'
  post 'admin/login', to: 'admin#authenticate', as: 'admin_auth'
  delete 'admin/logout', to: 'admin#logout', as: 'admin_logout'
  post 'admin/attend'
  post 'admin/call', to: 'admin#call_mail_send'
  post 'admin/apollo', to: 'admin#apollo_mail_send'
  post 'admin/cancel'

  # if Rails.env.development?
    # mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end

  match '*path' => 'application#rescue404', via: :all
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController
  before_action :get_attr, :except => [:time_select, :seat_select, :help, :message, :resend_mail, :resend]
  before_action :attr_check, :only => [:time_select, :seat_select]
  before_action :form_and_register_filter, :only => [:form, :register]
  before_action :auth_and_cancel_filter, :only => [:auth, :cancel_form, :cancel]

  def time_select
    @attrs = Attr.all
  end

  def seat_select
    @id = params[:id].to_i
    if @id % 10 != 1 || @id > 500 || @id < 0
      redirect_to message_path, alert: "このURLはみつからないのにゃん"
    else
      @attrs = Attr.limit(10).offset(@id.to_i - 1)
    end
  end

  def form
    @user = User.new
  end

  def register
    require 'digest'
    addr = user_params[:addr]
    @user = @attr.user.build(addr: addr, addr_confirmation: user_params[:addr_confirmation], url: Digest::SHA256.hexdigest(addr))

    if @user.save
        @attr.update(status: 1) unless @attr.time.today?
        RegistMailer.regist_bmail(@user, @attr).deliver
        redirect_to(message_path, notice: "確認メールを送信したにゃん")
    else
      render :form
    end
  end

  def auth
    if @attr.time - Time.now < 5.minutes
      redirect_to message_path, alert: "予約は終了したにゃん"
    else
      flag = @attr.status == 1 || @attr.time.today?
      if flag && @user && @user.attr_id == @attr.id
        if @user.update(status: 1)
          @attr.update(status: 2, authenticated_addr: @user.addr, authenticated_at: Time.zone.now)
          if Time.zone.now + 30.minutes > @attr.time
            @attr.update(mail1: true)
          end
          RegistMailer.regist_amail(@user, @attr).deliver
          redirect_to message_path, notice: "予約完了メールを送信したにゃん"
        else
          redirect_to message_path, alert: "この座席はうまってしまったにゃん"
        end
      else
        redirect_to message_path, alert: "このURLはみつからないのにゃん"
      end
    end
  end

  def resend
  end

  def resend_mail
    if (attr = Attr.find_by(authenticated_addr: params[:addr]))
      RegistMailer.regist_amail(attr.user.where(status: 1).last, attr).deliver
    end
    redirect_to message_url, alert: 'メールを送信したにゃん'
  end

  def cancel_form
    unless @user || @attr.status == 2 || @user.attr_id == @attr.id
      redirect_to message_path, alert: "このURLはみつからないのにゃん"
    end
  end

  def cancel
    if @user && @attr.status == 2 && @user.attr_id == @attr.id
      @user.update_attribute(:status, 2)
      @attr.update(status: 0, authenticated_addr: nil, authenticated_at: nil, attended: false, mail1: false, mail2: false)
      redirect_to message_path, notice: "予約をキャンセルしたにゃん"
    else
      redirect_to message_path, alert: "このURLはみつからないのにゃん"
    end
  end

  def message
    redirect_to root_path unless flash[:notice].present? || flash[:alert].present?
  end

  private
  def get_attr
    @attr = Attr.find(params[:id])
  end

  def form_and_register_filter
    redirect_to(message_path, {alert: "この座席はうまってしまったにゃん"}) unless @attr.status == 0
  end

  def attr_check
    @attr = Attr.where(status: 1).where("updated_at <= ?", 15.minutes.ago)
    @attr.update(status: 0) if @attr
  end

  def auth_and_cancel_filter
    @user = User.where(url: params[:key]).last
  end

  def user_params
    params.require(:user).permit(:addr, :addr_confirmation)
  end
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/views/reserve/cancel_form.html.erb
<div id="cancel-form">
  <h2>キャンセルフォーム</h2>

  <p>予約をキャンセルしてもいいですか？</p>

  <%= button_to('キャンセルする', { action: :cancel, id: @attr.id, key: @user.url },
                data: { :disable_with => "処理中..." }) %>
</div>

app/views/reserve/form.html.erb
<div class="time">
  <p>
    公演時間<br><span><%= @attr.time.strftime("%m/%d %H:%M") %></span>
  </p>
  <p>
    座席<br><span><%= seat_is(@attr.seat).join(' ') %></span>
  </p>
</div>

<div id="email-description">
  <h2>公演当日に受信可能なメールアドレスを入力してください</h2>
  <p>公演10分前までに受付にお越しにならない場合は<br>予約がキャンセルになります</p>
</div>

<% if @user.errors.any? %>
    <ul class="errors">
      <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<div id="email">
  <%= form_for @user, url: reserve_register_path(@attr.id) do |f| %>
      <%= f.email_field :addr, class: 'email_field', placeholder: 'メールアドレス' %>
      <%= f.email_field :addr_confirmation, class: 'email_field', placeholder: 'もう一度入力してください' %>
      <%= button_tag(type: 'submit', id: 'register',  data: { :disable_with => "送信中..." }) do %>
          送信<span class="space">&thinsp;</span>
      <% end %>
  <% end %>
</div>

app/views/reserve/help.html.erb
<div id="help">
  <% 7.times do |i| %>
    <% if i == 6 %>
      <%= link_to image_tag("help#{i+1}.jpg", width: 480), root_path %>
    <% else %>
      <%= image_tag "help#{i+1}.jpg", width: 480 %>
    <% end %>
  <% end %>
</div>

app/views/reserve/help_smart_phone.html.erb
<div id="help">
  <% 7.times do |i| %>
    <% if i == 6 %>
      <%= link_to image_tag("help#{i+1}.jpg", width: 320), root_path %>
    <% else %>
      <%= image_tag "help#{i+1}.jpg", width: 320 %>
    <% end %>
  <% end %>
</div>

app/views/reserve/message.html.erb
<% if notice.present? || alert.present? %>
  <div class="flash">
    <div class="arrow-box">
      <%= notice %><%= alert %>
      <%= image_tag('character.png') %>
    </div>
  </div>
<% end %>

app/views/reserve/remail_from.html.erb
  <%= form_tag action: :send_remail do%>
      <%= f.email_field :addr, class: 'email_field', placeholder: 'メールアドレス' %>
      <%= button_tag(type: 'submit', id: 'register',  data: { :disable_with => "送信中..." }) do %>
      送信<span class="space">&thinsp;</span>
      <% end %>
  <% end %>

app/views/reserve/resend.html.erb
<div id="resend-form">
  <h2>予約状況を確認</h2>

  <p>予約状況をメールで送信します。ご予約の際に使用したメールアドレスを入力してください。</p>
  <div id="email">
    <%= form_tag(reserve_resend_path) do %>
        <%= email_field_tag(:addr, '', class: 'email_field', placeholder: 'メールアドレス') %>
        <%= button_tag(type: 'submit', id: 'register',  data: { :disable_with => "送信中..." }) do %>
            送信<span class="space">&thinsp;</span>
        <% end %>
    <% end %>
  </div>
</div>

app/views/reserve/seat_select.erb
<div class="time">
  <p>
    公演時間<br><span><%= @attrs.first.time.strftime("%m/%d %H:%M") %></span>
  </p>
</div>
<div id="seat-select-pc">
  <% @attrs.each_with_index do |f, i| %>
    <% if i == 0 || i == 5 %>
      <div class="each-room cf">
      <% if i == 0 %>
        <p class="room-name">Room A</p>
      <% elsif i == 5 %>
        <p class="room-name">Room B</p>
      <% end %>
      <div id="screen">
        画面<span class="space">&thinsp;</span>
      </div>
    <% end %>
    <div id="seat-<%= i + 1 %>-pc">
      <div class="seat-img">
        <% if f.status == 0%>
            <%= link_to image_tag('seat.png', size: 80), reserve_form_path(f.id) %>
        <% else %>
            <%= image_tag('seat_soldout.png', size: 80) %>
        <% end %>
      </div>
      <div class="seat-label">
        <% case i % 5 + 1 %>
        <% when 1 %>
            S1
        <% when 2 %>
            S2
        <% when 3 %>
            S3
        <% when 4 %>
            A1
        <% else %>
            A2
        <% end %>
      </div>
    </div>
    <% if i == 4 || i == 9 %>
      </div>
    <% end %>
  <% end %>
  <div id="price-aria" class="cf">
    <p class="price">
      <span>前売り料金</span><br>
      S<span>席</span>: 300<span>円</span><br>
      A<span>席</span>: 200<span>円</span><br>
    </p>
    <p class="price">
      <span>当日料金</span><br>
      S<span>席</span>: 400<span>円</span><br>
      A<span>席</span>: 300<span>円</span><br>
    </p>
  </div>
</div>

app/views/reserve/seat_select.html.erb
<div class="time">
  <p>
    公演時間<br><span><%= @attrs.first.time.strftime("%m/%d %H:%M") %></span>
  </p>
</div>
<div id="seat-select-pc">
  <% @attrs.each_with_index do |f, i| %>
    <% if i == 0 || i == 5 %>
      <div class="each-room cf">
      <% if i == 0 %>
        <p class="room-name">Room A</p>
      <% elsif i == 5 %>
        <p class="room-name">Room B</p>
      <% end %>
      <div id="screen">
        画面<span class="space">&thinsp;</span>
      </div>
    <% end %>
    <div id="seat-<%= i + 1 %>-pc">
      <div class="seat-img">
        <% if f.status == 0%>
            <%= link_to image_tag('seat.png', size: 80), reserve_form_path(f.id) %>
        <% else %>
            <%= image_tag('seat_soldout.png', size: 80) %>
        <% end %>
      </div>
      <div class="seat-label">
        <% case i % 5 + 1 %>
        <% when 1 %>
            S1
        <% when 2 %>
            S2
        <% when 3 %>
            S3
        <% when 4 %>
            A1
        <% else %>
            A2
        <% end %>
      </div>
    </div>
    <% if i == 4 || i == 9 %>
      </div>
    <% end %>
  <% end %>
  <div id="price-aria" class="cf">
    <p class="price">
      <span>前売り料金</span><br>
      S<span>席</span>: 300<span>円</span><br>
      A<span>席</span>: 200<span>円</span><br>
    </p>
    <p class="price">
      <span>当日料金</span><br>
      S<span>席</span>: 400<span>円</span><br>
      A<span>席</span>: 300<span>円</span><br>
    </p>
  </div>
</div>

app/views/reserve/seat_select_smart_phone.html.erb
<div id="room-select" class="cf">
  <div id="room">Room<span class="space">&thinsp;</span></div>
  <div id="btn-a">A<span class="space">&thinsp;</span></div>
  <div id="btn-b">B<span class="space">&thinsp;</span></div>
</div>
<div class="time">
  <p>
    公演時間<br><span><%= @attrs.first.time.strftime("%m/%d %H:%M") %></span>
  </p>
</div>
<div id="seat-select">
  <div id="screen">
    画面<span class="space">&thinsp;</span>
  </div>
  <% count = 0 %>
  <% @attrs.each_with_index do |f, i| %>
    <% if i == 0 || i == 5 %>
      <div class="each-room">
    <% end %>
    <div id="seat-<%= i + 1 %>">
      <div class="seat-img">
        <% if f.status == 0%>
          <% if i <= 4
            count += 1
           else
            count -= 1
           end %>
          <%= link_to image_tag('seat.png', size: 80), reserve_form_path(f.id) %>
        <% else %>
          <%= image_tag('seat_soldout.png', size: 80) %>
        <% end %>
      </div>
      <div class="seat-label">
        <% case i % 5 + 1 %>
        <% when 1 %>
            S1
        <% when 2 %>
            S2
        <% when 3 %>
            S3
        <% when 4 %>
            A1
        <% else %>
            A2
        <% end %>
      </div>
    </div>
    <% if i == 4 || i == 9 %>
        </div>
    <% end %>
  <% end %>
  <p class="price" data-seat-id="<%= count %>">
    <span>前売り料金</span><br>
    S<span>席</span>: 300<span>円</span><br>
    A<span>席</span>: 200<span>円</span><br>
    <span>当日料金</span><br>
    S<span>席</span>: 400<span>円</span><br>
    A<span>席</span>: 300<span>円</span><br>
  </p>
</div>

app/views/reserve/time_select.html.erb
<div id="links">
  <%= link_to '予約の説明はこちら', help_path %>
  <%= link_to '予約情報の確認はこちら', reserve_resend_path %>
</div>
<div id="date-select" class="cf">
  <div id="time-table-label">タイムテーブル<span class="space">&thinsp;</span></div>
  <div id="date-29">10月29日<span class="space">&thinsp;</span></div>
  <div id="date-30">10月30日<span class="space">&thinsp;</span></div>
</div>

<div id="date-label" class="cf">
  <div id="time-label">開始時刻</div>
  <div id="progress-label">残り席数</div>
</div>

<div id="time-tables">
  <% count = 0 %>
  <% @attrs.each_with_index do |f, i|%>
    <% if i.between?(90, 99) || i.between?(190, 199) || i.between?(340, 349) || i.between?(440, 449) %>
      <% if i == 90 || i == 190 || i == 340 || i == 440 %>
        <div class="time-table rest-time" id="time-<%= i/10+1 %>">
          休憩時間
        </div>
      <% end %>
    <% else %>
      <% count += 1 if f.status == 0 %>
      <% if f.seat == 9 %>
          <div class="time-table" id="time-<%= (f.id+1)/10 %>">
            <% if f.time > Time.zone.now + 5.minutes %>
              <a href="<%= seat_select_path(f.id-9) %>"></a>
            <% else %>
              <div class="ended">予約終了</div>
            <% end %>
            <div class="left">
              <span><%= f.time.strftime("%H:%M") %></span>
            </div>
            <div class="right">
              <%= image_tag("#{count}.png") %>
            </div>
            <% count = 0 %>
          </div>
      <% end %>
    <% end %>
  <% end %>
</div>